[build]
builder = "dockerfile"

[deploy]
# startCommandを削除してDockerfileのCMDを使用
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
# 本番環境設定
[environments.production.variables]
ENVIRONMENT = "production"

[environments.development]
# 開発環境設定  
[environments.development.variables]
ENVIRONMENT = "development"

